services:

  nginx:
   image: nginx
   ports: 
    - 8080:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  server1:
    build: ./server
    env_file: ./server/.env
    environment:
      - SERVER_NAME=first server
    ports:
      - 3000:3000

  server2:
   build: ./server
   env_file: ./server/.env
   environment:
     - SERVER_NAME= second server
   ports:
    - 3001:3000
  server3:
   build: ./server
   env_file: ./server/.env
   environment:
     - SERVER_NAME= third server
   ports:
    - 3002:3000