events{

}

http{

    upstream backend{
        server server1:3000;
        server server2:3000;
        server server3:3000;
    }
    server{
        listen 80;
        location /{
            # return 200 "Hello from nginx";
            proxy_pass http://backend;
        }
    }
}